name: Generate Terminal GIF

on:
  push:
    branches:
      - main

jobs:
  generate-gif:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install gifos from GitHub
        run: pip install git+https://github.com/gifos/gifos.git

      - name: Run GIF generator
        run: python generate_gif.py

      - name: Commit GIF
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/ModuleMaster64/PythonProgramsV3.git
          git add assets/pythonprograms.gif
          git commit -m "Update terminal GIF"
          git push origin main
